version: 0.2
phases:
  install:
    commands:
      - npm install -g typescript
  pre_build:
     commands:
     - aws s3api put-object --bucket "s3://${BUCKET}/" --key "test"
     - aws s3 rm --recursive "s3://${BUCKET}/"
  build:
    commands:
    - tsc index.ts
artifacts:
  files:
    - index.js
    - error.html
    - Dev_Server.html
    - Stg_Server.html
    - Prod_Server.html
