version: 0.2

phases:
  install:
    commands:
      - npm install -g typescript
  build:
    commands:
      - aws s3 rm --recursive "s3://${BUCKET}/"
      - tsc index.ts
artifacts:
  files:
    - index.js
    - error.html
    - Dev_Server.html
    - Stg_Server.html
    - Prod_Server.html
